// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeBUAQFsCvQnm_Y9pKlQux6VuDyIGYJmk',
    appId: '1:252624721432:android:1c5e2041886712164f156d',
    messagingSenderId: '252624721432',
    projectId: 'integrity-link',
    storageBucket: 'integrity-link.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbCCNx715NLq0Js5_gLP0CBvpokYS7lDA',
    appId: '1:252624721432:ios:9c161064894648234f156d',
    messagingSenderId: '252624721432',
    projectId: 'integrity-link',
    storageBucket: 'integrity-link.appspot.com',
    androidClientId: '252624721432-r1rnpdb8obtk4hro1srqko4qi9rbi94p.apps.googleusercontent.com',
    iosClientId: '252624721432-887rtgbcgachb9tgbr2t5tednkf9r7mi.apps.googleusercontent.com',
    iosBundleId: 'com.pamodzi.integritylink',
  );
}
